FROM servicesdocker/archlinuxcn-base:latest

# 作者信息
MAINTAINER servicesdocker "2478557459@qq.com"

# 更新系统
RUN   yaourt -Syu --noconfirm

# 安装nvm
RUN  yaourt -Sy --noconfirm  devel

CMD [ "/bin/bash" ]


